// next
import Link from "next/link"
// styled
import styled from "styled-components"
// seo
import SEO from "../components/SEO"
// layout
import DefaultLayout from "../layouts/default"
// fontawesome
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome"
import { faGithub, faDiscord } from "@fortawesome/free-brands-svg-icons"

const IndexPage = styled.div`
  .lead {
    font-size: 1.2rem;
  }

  main {
    display: flex;
    justify-content: center;
    flex-direction: column;
    align-items: center;
    height: 45vh;
  }

  .btn {
    background: #000;
    color: #fff;
    font-size: 1.1rem;
  }
`

export default function Home() {
  return (
    <>
      <SEO>
        <meta name="description" content="Generated by create next app" />
        <meta content="unknown"/>
      </SEO>
      <DefaultLayout>
        <IndexPage>
          <div className="row">
            <div className="col-12">
              <main>

                <h1 className="animate" data-animation="title">Novalumo Developers</h1>
                <p className="lead animate" data-animation="title">
                  デベロッパーが、集う場所。
                </p>

                <section className="animate" data-animation="title">
                  <a href="https://github.com/novalumo-developers" target="_blank" rel="noopener noreferrer" className="btn">
                    <FontAwesomeIcon icon={faGithub} className="fa-fw me-2"/>GitHub
                  </a>
                  <a href="#" className="btn">
                    <FontAwesomeIcon icon={faDiscord} className="fa-fw me-2"/>Discord
                  </a>
                  <Link href="/get-started">
                    <a className="btn">Get Started</a>
                  </Link>
                </section>

              </main>
            </div>
          </div>
        </IndexPage>
      </DefaultLayout>
    </>
  )
}
