import Link from "next/link";
import styled from "@emotion/styled";
import SEO from "../components/SEO";
import DefaultLayout from "../layouts/default";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faGithub, faDiscord } from "@fortawesome/free-brands-svg-icons";
import {
  Box,
  Container,
  Heading,
  VStack,
  Text,
  Button,
  HStack,
} from "@chakra-ui/react";

const IndexPage = styled.div`
  main {
    display: flex;
    justify-content: center;
    flex-direction: column;
    align-items: center;
    height: 45vh;
  }

  .btn {
    background: #000;
    color: #fff;
    font-size: 1.1rem;
  }
`;

export default function Home() {
  return (
    <>
      <SEO>
        <meta name="description" content="Generated by create next app" />
        <meta content="unknown" />
      </SEO>
      <DefaultLayout>
        <IndexPage>
          <Container>
            <Box
              minHeight={"100vh"}
              display={"flex"}
              justifyContent={"center"}
              alignItems={"center"}
            >
              <VStack height={"100%"}>
                {/* text */}
                <Heading mb={-1} className="animate" data-animation="title">
                  Novalumo Developers
                </Heading>
                <Text fontSize="xl" className="animate" data-animation="title">
                  デベロッパーが、集う場所。
                </Text>
                {/* button */}
                <HStack className="animate" data-animation="title">
                  <Button
                    as="a"
                    href="https://github.com/novalumo-developers"
                    target="_blank"
                    rel="noopener noreferrer"
                    colorScheme={"blackAlpha"}
                  >
                    <FontAwesomeIcon icon={faGithub} />
                    GitHub
                  </Button>
                  <Link href="#" passHref>
                    <Button as="a" colorScheme={"blackAlpha"}>
                      <FontAwesomeIcon icon={faDiscord} />
                      Discord
                    </Button>
                  </Link>
                  <Link href="/#get-started" passHref>
                    <Button as={"a"} colorScheme={"blackAlpha"}>
                      Get Started
                    </Button>
                  </Link>
                </HStack>
              </VStack>
            </Box>
          </Container>
        </IndexPage>
      </DefaultLayout>
    </>
  );
}
